### ISSUE TITLE
expect_eof() when the eof token was already consumed fails with nonsense message

### ISSUE THREAD

**Issue by vdvman1** [vberlier/tokenstream#195]
Calling `stream.expect_eof()` when the `eof` token was already consumed raises the following exception:
```
File ".../tokenstream/stream.py", line 858, in expect
    raise self.emit_error(UnexpectedEOF(patterns))
tokenstream.error.UnexpectedEOF: Expected eof but reached end of file.
```

I would expect that `expect_eof()` would succeed if there are no tokens remaining, or if the only remaining token is the `eof` token.

This is my current workaround:
```py
token = stream.peek()
if token and token.type != "eof":
    raise set_location(stream.emit_error(UnexpectedToken(token, ("eof",))), token)
```

(The `("eof",)` is a 1-tuple to make pylance happy, pylance doesn't like passing `["eof"]` to a `*args` style parameter, and passing just `"eof"` ends up treating the string is invidual characters)

**Comment by vberlier** [comment]
Thanks for the bug report! As of [`v1.5.0`](https://github.com/vberlier/tokenstream/releases/tag/v1.5.0) `stream.expect_eof()` now succeeds even when the `eof` token was already consumed.
